package com.interview.incidentrca.controller;
import com.interview.incidentrca.dto.*;import com.interview.incidentrca.enums.*;import com.interview.incidentrca.exception.BadRequestException;import com.interview.incidentrca.service.IncidentService;import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.data.domain.*;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.time.Instant;import java.util.*;
@RestController @RequestMapping("/api/incidents") @RequiredArgsConstructor public class IncidentController{private final IncidentService service;
 @PostMapping @PreAuthorize("hasAnyRole('ADMIN','ENGINEER')") ResponseEntity<IncidentResponse> create(@Valid @RequestBody IncidentCreateRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(service.create(r));}
 @GetMapping Page<IncidentResponse> all(@RequestParam(required=false) IncidentStatus status,@RequestParam(required=false) Severity severity,@RequestParam(required=false) String serviceName,@RequestParam(required=false) Long assignedEngineerId,@RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME) Instant from,@RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME) Instant to,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="10") int size,@RequestParam(defaultValue="createdAt,desc") String sort){return service.search(status,severity,serviceName,assignedEngineerId,from,to,pageable(page,size,sort));} 
 @GetMapping("/{id}") IncidentResponse get(@PathVariable Long id){return service.get(id);} @PutMapping("/{id}") @PreAuthorize("hasAnyRole('ADMIN','ENGINEER')") IncidentResponse update(@PathVariable Long id,@Valid @RequestBody IncidentUpdateRequest r){return service.update(id,r);} @DeleteMapping("/{id}") @PreAuthorize("hasRole('ADMIN')") ResponseEntity<Void> delete(@PathVariable Long id){service.delete(id);return ResponseEntity.noContent().build();}
 @PatchMapping("/{id}/status") @PreAuthorize("hasAnyRole('ADMIN','ENGINEER')") IncidentResponse status(@PathVariable Long id,@Valid @RequestBody StatusUpdateRequest r){return service.changeStatus(id,r);} @PatchMapping("/{id}/assign") @PreAuthorize("hasAnyRole('ADMIN','ENGINEER')") IncidentResponse assign(@PathVariable Long id,@Valid @RequestBody AssignRequest r){return service.assign(id,r);} @PostMapping("/{id}/comments") @PreAuthorize("hasAnyRole('ADMIN','ENGINEER')") ResponseEntity<TimelineEventResponse> comment(@PathVariable Long id,@Valid @RequestBody CommentRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(service.comment(id,r));}
 @GetMapping("/{id}/timeline") List<TimelineEventResponse> timeline(@PathVariable Long id){return service.timeline(id);} @GetMapping("/{id}/root-cause-suggestions") List<RootCauseSuggestionResponse> rca(@PathVariable Long id){return service.suggestions(id);} @GetMapping("/{id}/duplicates") List<DuplicateIncidentResponse> duplicates(@PathVariable Long id){return service.duplicates(id);}
 private Pageable pageable(int page,int size,String sort){if(page<0)throw new BadRequestException("page must be 0 or greater");if(size<1||size>100)throw new BadRequestException("size must be between 1 and 100");String[] parts=sort.split(",",2);String field=parts[0].trim();Set<String> allowed=Set.of("id","title","severity","status","createdAt","updatedAt","resolvedAt");if(!allowed.contains(field))throw new BadRequestException("sort must be one of "+allowed+" with optional direction, example createdAt,desc");Sort.Direction direction=parts.length>1&&"asc".equalsIgnoreCase(parts[1].trim())?Sort.Direction.ASC:Sort.Direction.DESC;return PageRequest.of(page,size,Sort.by(direction,field));} }
